# Minimal topology for feature testing, not load.
orchestration:
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  pvcSize: 5Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi

optimize:
  enabled: false
