elasticsearch:
  enabled: true
global:
  ingress:
    enabled: true
    className: nginx
    host: "example.camunda.com"
    tls:
      enabled: true
      secretName: "tls-secret"
  elasticsearch:
    enabled: true
orchestration:
  gateway:
    grpc:
      enabled: true
  contextPath: "/"
  ingress:
    grpc:
      enabled: true
      host: "grpc.example.camunda.com"
      path: "/"
      tls:
        enabled: true
        secretName: "grpc-tls-secret"
  data:
    secondaryStorage:
      type: elasticsearch
prometheusServiceMonitor:
  enabled: true
connectors:
  enabled: true
